### PR TITLE
fix: applies isEnabled condition to parse_ini_file function call

### LINKED ISSUE #47: If the parse_ini_file() method is in the disabled_function list in php.ini
**Describe the bug**
'I am getting an error in the line "parse_ini_file($iniPath);" in the JsonMapper.php file. In php.ini, this method "parse_ini_file" is in the "disable_functions" list. 
Error message: "Fatal error: Uncaught Error: Call to undefined function apimatic\jsonmapper\parse_ini_file()". 

**Expected behavior**
if it is not in the disabled function here, can you add the control?

**Screenshots**
resim

### PR DESCRIPTION
**Pull request by asadali214**
## What
This PR adds a condition to calling `parse_ini_file()`, by checking if it doesn't exist in the disabled functions list

## Why
The disable_functions list in php.ini might contain parse_ini_file function call, as it parses the `.ini` file which tends to contain sensitive information apart from the required configuration.

Closes #47 

## Type of change
Select multiple if applicable.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause a breaking change)
- [ ] Tests (adds or updates tests)
- [ ] Documentation (adds or updates documentation)
- [ ] Refactor (style improvements, performance improvements, code refactoring)
- [ ] Revert (reverts a commit)
- [ ] CI/Build (adds or updates a script, change in external dependencies)

## Dependency Change
N/A

## Breaking change
This PR does not introduce any breaking changes

## Testing
I have tested this change by adding `parse_ini_file` to the disable_functions option in php.ini file

## Checklist
- [X] My code follows the coding conventions
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added new unit tests

### CODE REVIEW

File: src/JsonMapper.php [hunk 1]
```diff
@@ -125,8 +125,12 @@ function __construct()
 
         if (!isset($this->config)) {
             $iniPath = php_ini_loaded_file();
+            $functionEnabled = !in_array(
+                'parse_ini_file',
+                explode(',', ini_get('disable_functions'))
+            );
             $accessAllowed = $this->isPathAllowed($iniPath, ini_get('open_basedir'));
-            if ($accessAllowed && is_readable($iniPath)) {
+            if ($accessAllowed && $functionEnabled && is_readable($iniPath)) {
```
Comment (sufyankhanrao) [inline src/JsonMapper.php:133]: Question: Can we add unit tests for this logic? If yes then we must add it.

Comment (asadali214) [reply src/JsonMapper.php:133]: This setting is controlled via the installed PHP version through `php.ini` configuration file. There is no way to disable functions at runtime according to the [PHP Manual](https://www.php.net/manual/en/ini.core.php#ini.disable-functions). It said you cannot set this in `httpd.conf`

This is the reason that I have to test it manually as we can not write unit tests^

**Review by sufyankhanrao — APPROVED** [review]
