### PR TITLE
Move exception messages to JsonMapperException.

### LINKED ISSUE #15: Move exception messages to JsonMapperException
All exception messages can be moved to [JsonMapperException](https://github.com/apimatic/jsonmapper/blob/master/src/JsonMapperException.php) class for an improved code structure and readability; as in: https://github.com/apimatic/jsonmapper/blob/731ecf23abb4812cd9f297e7b968c91b64c368cc/src/JsonMapperException.php#L34-L44

### PR DESCRIPTION
**Pull request by Mohammad-Haris**
Closes #15.

### CODE REVIEW

File: src/JsonMapper.php [hunk 1]
```diff
@@ -214,10 +214,8 @@ public function map($json, $object, $forMultipleTypes = false)
 
             if (!$hasProperty) {
                 if ($this->bExceptionOnUndefinedProperty) {
-                    throw new JsonMapperException(
-                        'JSON property "' . $key . '" does not exist'
-                        . ' in object of type ' . $strClassName
-                    );
+                    throw JsonMapperException
+                    ::undefinedPropertyException($key, $strClassName);
```
Comment (asadali214) [inline src/JsonMapper.php:218]: There must be additional 4 spaces indent after moving a sub-statement to the next line, this applies to the whole file

File: src/JsonMapper.php [hunk 2]
```diff
@@ -229,11 +227,10 @@ public function map($json, $object, $forMultipleTypes = false)
 
             if ($accessor === null) {
                 if ($this->bExceptionOnUndefinedProperty) {
-                    throw new JsonMapperException(
-                        'JSON property "' . $key . '" has no public setter method'
-                        . ' in object of type ' . $strClassName
-                    );
+                    throw JsonMapperException
+                    ::undefinedPropertyException($key, $strClassName, true);
```
Comment (asadali214) [inline src/JsonMapper.php:231]: Also instead of breaking the statement like this, In PHP we move the each of  the arguments to the next lines

File: src/JsonMapper.php (hunk 1 above)
Comment (asadali214) [reply src/JsonMapper.php]: @Mohammad-Haris

File: src/JsonMapper.php (hunk 2 above)
Comment (asadali214) [reply src/JsonMapper.php]: @Mohammad-Haris

**Review by asadali214 — APPROVED** [review]
Approved, but do take a look at my commits to see the fixes that I have done @Mohammad-Haris
